add tests
DawidDamek/games_online pull request #4
Opened 2022-07-07 15:29 UTC by DawidDamek

2022-07-07 20:10 UTC, wozny1989 requested changes
Small feedback ✌️

2022-07-07 20:10 UTC, wozny1989 commented on app/components/whac-a-mole/game/interface/template.hbs
> +      data-test-hard-button
same ☝️

2022-07-08 06:29 UTC, DawidDamek commented on tests/integration/whac-a-mole/game/component-test.js
> +      }
Without constructor tiimeout set on 3000 wasn't working properly. :/

2022-07-08 11:53 UTC, wozny1989 approved these changes

2022-07-08 11:53 UTC, merged